# SPDX-License-Identifier: AGPL-3.0-only
"""SuperCollider NRT rendering for the vibe parts (Spec 5 vertical slice).

Renders kick (from drums), bass, and pad through the designed patches in
``render/patches.scd`` via headless ``sclang`` non-realtime synthesis, then
mixes them with FluidSynth GM stems of the remaining parts into
``vibe_mix.wav``. Deterministic end to end: patches use no random UGens and
NRT scores are derived from the same seeded events as ``setloom generate``.

Usage: ``uv run python -m setloom.scrender <spec.yml> <variant-dir> [--seed S] [--variant N]``
"""

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

from setloom.midi import PPQ, NoteEvent, total_ticks
from setloom.parts import ALL_PARTS, part_rng
from setloom.schema import TrackSpec, load_spec

SC_APP_SCLANG = "/Applications/SuperCollider.app/Contents/MacOS/sclang"
PATCHES = Path(__file__).resolve().parents[2] / "render" / "patches.scd"

KICK_NOTE = 36

# Which generated parts feed which patch; kick events are the drum part's
# kick notes only (hats/perc stay in the GM layer for this slice).
VIBE_PARTS = ("kick", "bass", "pad")
GM_PARTS = ("drums_nokick", "chords", "arp", "lead", "fills", "shaker", "clap_ride", "fx")

# Mix gains: SC stems carry the low end; GM texture sits behind them.
MIX_GAINS = {"kick": 1.0, "bass": 0.9, "pad": 0.8, "gm": 0.55}

SYNTH_FOR_PART = {"kick": "vibe_kick", "bass": "vibe_bass", "pad": "vibe_pad"}


def find_sclang() -> str | None:
    return shutil.which("sclang") or (SC_APP_SCLANG if Path(SC_APP_SCLANG).exists() else None)


def ticks_to_seconds(ticks: int, bpm: float) -> float:
    return ticks * 60.0 / (bpm * PPQ)


def export_score(events: list[NoteEvent], bpm: float) -> list[dict]:
    """NoteEvents -> JSON-able score rows (deterministic, sorted)."""
    rows = [
        {
            "note": e.note,
            "amp": round(e.velocity / 127, 4),
            "start": round(ticks_to_seconds(e.start_tick, bpm), 6),
            "dur": round(ticks_to_seconds(e.duration_ticks, bpm), 6),
        }
        for e in events
    ]
    return sorted(rows, key=lambda r: (r["start"], r["note"]))


def vibe_events(spec: TrackSpec, seed: int, variant: int) -> dict[str, list[NoteEvent]]:
    """The three vibe parts' events, derived exactly like ``setloom generate``."""
    drums = ALL_PARTS["drums"].generate(spec, part_rng(seed, variant, "drums"))
    return {
        "kick": [e for e in drums if e.note == KICK_NOTE],
        "bass": ALL_PARTS["bass"].generate(spec, part_rng(seed, variant, "bass")),
        "pad": ALL_PARTS["pad"].generate(spec, part_rng(seed, variant, "pad")),
    }


def build_scd(part: str, score: list[dict], bpm: float, total_seconds: float, out_wav: str) -> str:
    """One self-contained sclang NRT script for a part stem (deterministic text)."""
    synth = SYNTH_FOR_PART[part]
    pump_rate = round(bpm / 60.0, 6)
    note_rows = ",\n".join(
        f"    [{row['start']}, {row['note']}, {row['amp']}, {row['dur']}]" for row in score
    )
    tail = 4.0 if part == "pad" else 1.0
    return f"""// generated by setloom.scrender — do not edit
(
var defs, score, bundles, notes;
defs = "{PATCHES}".load;
notes = [
{note_rows}
];
bundles = defs.collect {{ |d| [0.0, ['/d_recv', d.asBytes]] }};
notes.do {{ |n|
    bundles = bundles.add([
        n[0] + 0.05,
        ['/s_new', '{synth}', -1, 0, 0,
         'freq', n[1].midicps, 'amp', n[2], 'sustain', n[3], 'pumpRate', {pump_rate}]
    ]);
}};
bundles = bundles.add([{round(total_seconds, 3)} + 0.05 + {tail}, [0]]);
score = Score(bundles);
score.recordNRT(
    outputFilePath: "{out_wav}",
    sampleRate: 44100,
    headerFormat: "WAV",
    sampleFormat: "int16",
    options: ServerOptions.new.numOutputBusChannels_(2).memSize_(2 ** 18),
    action: {{ "RENDER-DONE {part}".postln; 0.exit }}
);
)
"""


def render_part_stem(
    part: str,
    events: list[NoteEvent],
    spec: TrackSpec,
    out_wav: Path,
    sclang: str,
    workdir: Path,
) -> None:
    score = export_score(events, spec.bpm)
    seconds = ticks_to_seconds(total_ticks(spec), spec.bpm)
    scd = build_scd(part, score, spec.bpm, seconds, str(out_wav))
    scd_path = workdir / f"render-{part}.scd"
    scd_path.write_text(scd, encoding="utf-8")
    result = subprocess.run(
        [sclang, str(scd_path)], capture_output=True, text=True, timeout=600
    )
    if f"RENDER-DONE {part}" not in result.stdout or not out_wav.exists():
        raise RuntimeError(f"sclang render failed for {part}:\n{result.stdout[-2000:]}")


def mix(variant_dir: Path, sc_stems: dict[str, Path], out_wav: Path) -> None:
    """sox mix: SC stems at full weight, existing GM full render as the texture bed."""
    gm_full = variant_dir / "full.wav"
    cmd = ["sox", "-m"]
    for part, stem in sc_stems.items():
        cmd += ["-v", str(MIX_GAINS[part]), str(stem)]
    if gm_full.exists():
        cmd += ["-v", str(MIX_GAINS["gm"]), str(gm_full)]
    cmd += [str(out_wav)]
    subprocess.run(cmd, check=True, capture_output=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render vibe stems via SuperCollider NRT")
    parser.add_argument("spec")
    parser.add_argument("variant_dir")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--variant", type=int, default=1)
    args = parser.parse_args(argv)

    sclang = find_sclang()
    if sclang is None:
        print("sclang not found — install SuperCollider", file=sys.stderr)
        return 1
    spec = load_spec(args.spec)
    seed = spec.seed if args.seed is None else args.seed
    variant_dir = Path(args.variant_dir)
    variant_dir.mkdir(parents=True, exist_ok=True)

    events = vibe_events(spec, seed, args.variant)
    stems: dict[str, Path] = {}
    for part in VIBE_PARTS:
        stem = variant_dir / f"stem-{part}.wav"
        render_part_stem(part, events[part], spec, stem, sclang, variant_dir)
        stems[part] = stem
        print(f"rendered {stem.name}")
    out = variant_dir / "vibe_mix.wav"
    mix(variant_dir, stems, out)
    print(f"mixed {out}")
    print("reminder: candidates require human listening notes before approval")
    return 0


def export_score_json(events: list[NoteEvent], bpm: float) -> str:
    """Stable JSON for tests/interop."""
    return json.dumps(export_score(events, bpm), sort_keys=True)


if __name__ == "__main__":
    raise SystemExit(main())
